#!/bin/sh

docker run \
	--rm \
	--net=host \
	--name libreoffice \
	-e DISPLAY=unix$DISPLAY \
	-v $HOME:/home/bwen \
	-v /etc/localtime:/etc/localtime:ro \
        -v /tmp/.X11-unix:/tmp/.X11-unix \
	-e GDK_SCALE \
	-e GDK_DPI_SCALE \
	apps/libreoffice

