#!/bin/sh


docker run \
	--rm \
	--net=host \
	--ipc=host \
	--memory="500m" \
	--name postman \
	-e DISPLAY=$DISPLAY \
	-u $(id -u):1000 \
        -v /tmp/.X11-unix:/tmp/.X11-unix \
	-v ${HOME}/.Xauthority:/home/gui/.Xauthority \
	-v postman_home:/home/gui/Postman \
	-v postman_cache:/home/gui/.cache \
	-v postman_swt:/home/gui/.swt \
        -v /dev/shm:/dev/shm \
	apps/postman

