#!/bin/sh

GIT_PROFILES=""

if [[ -f "${HOME}/.gitconfig" ]]; then
  GIT_PROFILES="-v ${HOME}/.gitconfig:/home/gui/.gitconfig"
fi

if [[ -f "${HOME}/.gitconfig-work" ]]; then
  GIT_PROFILES="${GIT_PROFILES} -v ${HOME}/.gitconfig-work:/home/gui/.gitconfig-work"
fi

if [[ -f "${HOME}/.gitconfig-personal" ]]; then
  GIT_PROFILES="${GIT_PROFILES} -v ${HOME}/.gitconfig-personal:/home/gui/.gitconfig-personal"
fi

docker run \
	--rm \
	--net=host \
	--memory 2048mb \
	--name phpstorm \
	-e DISPLAY=$DISPLAY \
	-u $(id -u):1000 \
	-v /etc/localtime:/etc/localtime:ro \
        -v /tmp/.X11-unix:/tmp/.X11-unix \
	-v ${HOME}/.Xauthority:/home/gui/.Xauthority \
	-v ${HOME}/Workspace:/home/gui/Workspace \
	$GIT_PROFILES \
	-v phpstorm_java:/home/gui/.java \
	-v phpstorm_cache:/home/gui/.cache \
	-v phpstorm_config:/home/gui/.config \
	-v phpstorm_plugins:/gui-app/plugins \
	-v phpstorm_license:/gui-app/license \
	-v /etc/hosts:/etc/hosts \
        -v /dev/shm:/dev/shm \
	apps/phpstorm 

