#!/bin/sh

docker run \
	--rm \
	--net=host \
	--memory 1024mb \
	--name dbeaver \
	-e DISPLAY=$DISPLAY \
	-u $(id -u):1000 \
        -v /tmp/.X11-unix:/tmp/.X11-unix \
	-v ${HOME}/.Xauthority:/home/gui/.Xauthority \
	-v ${HOME}/Downloads:/home/gui/Downloads \
	-v dbeaver_java:/home/gui/.java \
	-v dbeaver_local:/home/gui/.local \
	-v dbeaver_cache:/home/gui/.eclipse \
        -v /dev/shm:/dev/shm \
	apps/dbeaver 

